export const LoginScreenRoute = "domain/auth/screens/Login"
export const RegisterScreenRoute = "domain/auth/screens/Register"
export const EventHomeScreenRoute = "domain/events/screens/EventHome"
export const EventSearchScreenRoute = "domain/events/screens/EventSearch"
export const LoadingScreenRoute = "domain/system/screens/Loading"